# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7f82d2408490b4ac6eccb71c70068742"
name = "fsoft-wishlist"
handle = "fsoft-wishlist"
application_url = "https://flood-verification-nations-tyler.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "appteststore01.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://flood-verification-nations-tyler.trycloudflare.com/auth/callback",
  "https://flood-verification-nations-tyler.trycloudflare.com/auth/shopify/callback",
  "https://flood-verification-nations-tyler.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
